name: Run Scraper

on:
  schedule:
    - cron: '0 */2 * * *'  # co 2h
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python main.py

      - name: Commit CSV
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          for file in oferty_mieszkan.csv prev_oferty.csv notify.flag; do
            if [ -f "$file" ]; then git add "$file"; fi
          done
          git commit -m "Update CSV" || echo "No changes"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main


      - name: Check for new offers
        id: check_notify
        run: |
          FLAG=$(cat notify.flag)
          echo "notify=$FLAG" >> $GITHUB_OUTPUT

      - name: Send SMS if new offers found
        if: steps.check_notify.outputs.notify == 'yes'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM_NUMBER }}
          TWILIO_TO: ${{ secrets.TWILIO_TO_NUMBER }}
        run: |
          curl -X POST https://api.twilio.com/2010-04-01/Accounts/$TWILIO_ACCOUNT_SID/Messages.json \
          --data-urlencode "To=whatsapp:$TWILIO_TO_NUMBER" \
          --data-urlencode "From=whatsapp:$TWILIO_FROM_NUMBER" \
          --data-urlencode "Body=📢 Nowe oferty: https://raw.githubusercontent.com/Kirizaki/scraper/main/wyniki.csv" \
          -u "$TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN"
