name: Run Scraper

on:
  schedule:
    - cron: '0 */2 * * *'  # co 2 godziny, o pełnej godzinie
  workflow_dispatch:       # pozwala ręcznie odpalić

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python main.py

      - name: Commit CSV
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add *.csv
          git commit -m "Update CSV" || echo "No changes to commit"
          git push
